### ISSUE TITLE
Change size for circles

### ISSUE THREAD

**Issue by remisaado** [nickjanssen/react-native-swipe-a-lot#7]
Is it possible to change the size of the circles? If so, how? I have an app where the circles are taking up too much space on some devices so that not all are visible on the screen, some are outside. I made the margin between them smaller and it worked on some devices, but on other devices they are still taking up too much space for the width of the screen.

These two parameters exist but are they for the circles only? And if so, what is PixelRatio? How do I change the width and height?

```
  width: PixelRatio.getPixelSizeForLayoutSize(6),
  height: PixelRatio.getPixelSizeForLayoutSize(6),
```

**Comment by dethell** [comment]
These two parameters are for the circles only. To get PixelRatio to work just import it from 'react-native'. Here is an example:

    import {PixelRatio} from 'react-native';
    ...
    <SwipeALot circleDefaultStyle={{width: PixelRatio.getPixelSizeForLayoutSize(3), height: PixelRatio.getPixelSizeForLayoutSize(3)}}>
        <Text>Some Details</Text>
    </SwipeALot>

**Comment by remisaado** [comment]
Yeah, figured this out a while ago, thanks anyway!
